// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuPbcQ99dGSQdbcCThrumzPsI5Gsl4T4',
    appId: '1:330325716500:web:cb72950fdd9fbb96b40101',
    messagingSenderId: '330325716500',
    projectId: 'dish-recipes-project',
    authDomain: 'dish-recipes-project.firebaseapp.com',
    storageBucket: 'dish-recipes-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAetXQP-f2E5KH5IFPEUS3ryLqZSsZoDN8',
    appId: '1:330325716500:android:43a0e797fbecd96cb40101',
    messagingSenderId: '330325716500',
    projectId: 'dish-recipes-project',
    storageBucket: 'dish-recipes-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtdIvZlNLTr5_tmJ6XtyQ-sNTz7CRVB0',
    appId: '1:330325716500:ios:52a51f8df72a75a4b40101',
    messagingSenderId: '330325716500',
    projectId: 'dish-recipes-project',
    storageBucket: 'dish-recipes-project.firebasestorage.app',
    iosBundleId: 'com.example.dishRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGtdIvZlNLTr5_tmJ6XtyQ-sNTz7CRVB0',
    appId: '1:330325716500:ios:52a51f8df72a75a4b40101',
    messagingSenderId: '330325716500',
    projectId: 'dish-recipes-project',
    storageBucket: 'dish-recipes-project.firebasestorage.app',
    iosBundleId: 'com.example.dishRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjuPbcQ99dGSQdbcCThrumzPsI5Gsl4T4',
    appId: '1:330325716500:web:db7f713c54b1ad88b40101',
    messagingSenderId: '330325716500',
    projectId: 'dish-recipes-project',
    authDomain: 'dish-recipes-project.firebaseapp.com',
    storageBucket: 'dish-recipes-project.firebasestorage.app',
  );

}